language: c++

cache:
  ccache: true

addons:
  apt:
    update: true
    packages:
      - clang
      - clang-format
      - llvm
      - llvm-dev
      - lcov
      - ruby
      - gcc-12
      - g++-12

jobs:
  include:
    - name: "Static Analysis"
      os: linux
      dist: jammy
      env:
        - RUN_TYPE=static-analysis
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - name: "Sanitizer"
      os: linux
      dist: jammy
      env:
        - RUN_TYPE=sanitizer
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - name: "Coverage"
      os: linux
      dist: jammy
      env:
        - RUN_TYPE=coverage
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - name: "GCC Unit Tests"
      os: linux
      dist: jammy
      env:
        - RUN_TYPE=test
        - MATRIX_EVAL="CC=gcc-12 && CXX=g++-12"
    - name: "Clang Unit Tests"
      os: linux
      dist: jammy
      env:
        - RUN_TYPE=test
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - tools/ci/install.sh

script:
  - tools/ci/build.sh && tools/ci/test.sh

after_success:
  - tools/ci/after_success.sh

notifications:
  slack:
    secure: dO+bR69Uu8PBZcFn2Et0ES66sZfxbOytMJBPLagMnp4yfjmeowKgjvzYaGu/LcW8PEHL0EWN+ZJqa3DIq/y6LMQP8E3WcyKZa8U6i48j8+RHgfbfd2PyXuGO6LmLdGVkndxX0MA3oQaKjk1iPwvjdB883Pm6hEFg97+ia0rD+RrfeiCJQFvDGn8QyLHMQQEL1JuTedZffTtBIgep7LPC7CEzaejx8ic/l6/FrqjCEIpTw82pPm2r43wNi+d4X5ieXzk09sy9lzO3MnBXrFVZmFu4hpg1Z1m+EyWUCtYuRGtN78Cc5DBVQq8l50PQge2OKLP5OBCOP97VZ78Z4MgkubpqDItABYEeO+O+jViGj/yXQq2PrOMscrSzvHsAOEtCpJkPftKj7cnCyjLBfAJ3S4zB4id3uRoV+vgmMRJAqDXEuYWssg5V+Nwy06W/3ObWp06p5eR1t8naGksy9X+/pYMz9CTdgL+LoGOhYXCA5yw1ajh2cS63S6GxRcP8GSQT0w2VzK5EFL2KmKWfqgxZ1OPFuO8R6nnf/iwwxI90r1FSzP4x+0MSBh5pN4Ic75/CFQVaYF+rgfmb85aFyxB209GQTrDwW9qKTvAta948xhEE31Mht6lSey8zhFNLNGgHKDflxciMu4DA1G6IuI5YBZgYFJgZbZ5IUrOndtMAZ+M=
    on_success: never
